import React, { FC } from "react";
import "./DisclaimerScreen.css";
import { useNavigate } from "react-router-dom";

const DisclaimerScreen: FC = () => {
    const navigate = useNavigate();

    const handleAccept = () => {
        navigate("/summary");
    };

    return (
        <div id="disclaimer-screen">
            <div className="disclaimer-container">
                <h1>Disclaimer</h1>
                <p>
                    By using this product, you acknowledge and accept that:
                </p>
                <ul className="disclaimer-list">
                    <li>
                        Summaries generated by this application are AI-generated and may not always be accurate, complete, or suitable for professional or academic use.
                    </li>
                    <li>
                        Users are responsible for reviewing the generated content and ensuring its appropriateness for their needs.
                    </li>
                    <li>
                        This tool is provided for informational purposes only and should not replace human judgment or expertise.
                    </li>
                </ul>
                <p>
                    By clicking "Accept" and continuing to use this product, you agree to these terms.
                </p>
            </div>
        </div>
    );
};

export default DisclaimerScreen;
